# Generated by Django 4.2.7 on 2023-12-16 06:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=100, null=True, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='User Name')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Last Name')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_image', models.ImageField(blank=True, default='cover-book-quran.jpg', null=True, upload_to='users/images')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('profile_cover_image', models.ImageField(blank=True, default='cover-book-quran.jpg', null=True, upload_to='users/covers')),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('ordered', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_of_templates', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_downloads', models.IntegerField(blank=True, default=0, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_facebook', models.URLField(blank=True, null=True)),
                ('contact_twitter', models.URLField(blank=True, null=True)),
                ('number_of_gifts', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('pro', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='profiles', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='profiles', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
