# Generated by Django 5.0.1 on 2024-01-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='number_of_downloads',
            new_name='number_of_paid',
        ),
        migrations.RemoveField(
            model_name='item',
            name='number_pages',
        ),
        migrations.RemoveField(
            model_name='item',
            name='version',
        ),
        migrations.AddField(
            model_name='item',
            name='colors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='heigth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lenght',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='number_in_meter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='thickness',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='withtransport',
            field=models.BooleanField(default=False, help_text='0=defauwithout transport, 1=withtransport'),
        ),
    ]
