# Generated by Django 5.0.1 on 2024-01-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_colors_remove_item_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='item',
            name='colors',
            field=models.ManyToManyField(default=1, max_length=55, to='core.colors'),
        ),
    ]
