# Generated by Django 5.0.1 on 2024-01-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_item_subcategory_item_colors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='withtransport',
            new_name='with_transport',
        ),
        migrations.AlterField(
            model_name='item',
            name='colors',
            field=models.ManyToManyField(default=1, to='core.colors'),
        ),
    ]
