# Generated by Django 5.0.1 on 2024-01-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_withtransport_item_with_transport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='colors',
            field=models.ManyToManyField(default='gray', to='core.colors'),
        ),
        migrations.AlterField(
            model_name='item',
            name='heigth',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='lenght',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='number_in_meter',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='thickness',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
