# Generated by Django 5.0.1 on 2024-01-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_item_colors_alter_item_heigth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='heigth',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='lenght',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='number_in_meter',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='thickness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
