# Generated by Django 4.2.7 on 2023-12-16 06:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('qunatity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(blank=True)),
                ('payment_id', models.CharField(blank=True, default=uuid.uuid4, max_length=150)),
                ('stats', models.CharField(choices=[('pending', 'pending'), ('out for Shipping', 'out for Shipping'), ('Completed', 'Completed')], default='pending', max_length=150)),
                ('message', models.TextField(blank=True, null=True)),
                ('tracking_no', models.CharField(blank=True, max_length=150)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True)),
                ('quantity', models.IntegerField(blank=True, default=1)),
            ],
        ),
    ]
